# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: HPC_phi_sim_data.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='HPC_phi_sim_data.proto',
  package='SavedSimulations',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x16HPC_phi_sim_data.proto\x12\x10SavedSimulations\"\xbb\x01\n\x0eSimulationData\x12G\n\tparameter\x18\x01 \x03(\x0b\x32\x34.SavedSimulations.SimulationData.ParameterFieldEntry\x12\x11\n\tspike_phi\x18\x02 \x03(\x02\x1aM\n\x13ParameterFieldEntry\x12\x10\n\x03key\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x12\n\x05value\x18\x02 \x01(\x02H\x01\x88\x01\x01\x42\x06\n\x04_keyB\x08\n\x06_valueb\x06proto3'
)




_SIMULATIONDATA_PARAMETERFIELDENTRY = _descriptor.Descriptor(
  name='ParameterFieldEntry',
  full_name='SavedSimulations.SimulationData.ParameterFieldEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='SavedSimulations.SimulationData.ParameterFieldEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='SavedSimulations.SimulationData.ParameterFieldEntry.value', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_key', full_name='SavedSimulations.SimulationData.ParameterFieldEntry._key',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_value', full_name='SavedSimulations.SimulationData.ParameterFieldEntry._value',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=155,
  serialized_end=232,
)

_SIMULATIONDATA = _descriptor.Descriptor(
  name='SimulationData',
  full_name='SavedSimulations.SimulationData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='parameter', full_name='SavedSimulations.SimulationData.parameter', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='spike_phi', full_name='SavedSimulations.SimulationData.spike_phi', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_SIMULATIONDATA_PARAMETERFIELDENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=232,
)

_SIMULATIONDATA_PARAMETERFIELDENTRY.containing_type = _SIMULATIONDATA
_SIMULATIONDATA_PARAMETERFIELDENTRY.oneofs_by_name['_key'].fields.append(
  _SIMULATIONDATA_PARAMETERFIELDENTRY.fields_by_name['key'])
_SIMULATIONDATA_PARAMETERFIELDENTRY.fields_by_name['key'].containing_oneof = _SIMULATIONDATA_PARAMETERFIELDENTRY.oneofs_by_name['_key']
_SIMULATIONDATA_PARAMETERFIELDENTRY.oneofs_by_name['_value'].fields.append(
  _SIMULATIONDATA_PARAMETERFIELDENTRY.fields_by_name['value'])
_SIMULATIONDATA_PARAMETERFIELDENTRY.fields_by_name['value'].containing_oneof = _SIMULATIONDATA_PARAMETERFIELDENTRY.oneofs_by_name['_value']
_SIMULATIONDATA.fields_by_name['parameter'].message_type = _SIMULATIONDATA_PARAMETERFIELDENTRY
DESCRIPTOR.message_types_by_name['SimulationData'] = _SIMULATIONDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SimulationData = _reflection.GeneratedProtocolMessageType('SimulationData', (_message.Message,), {

  'ParameterFieldEntry' : _reflection.GeneratedProtocolMessageType('ParameterFieldEntry', (_message.Message,), {
    'DESCRIPTOR' : _SIMULATIONDATA_PARAMETERFIELDENTRY,
    '__module__' : 'HPC_phi_sim_data_pb2'
    # @@protoc_insertion_point(class_scope:SavedSimulations.SimulationData.ParameterFieldEntry)
    })
  ,
  'DESCRIPTOR' : _SIMULATIONDATA,
  '__module__' : 'HPC_phi_sim_data_pb2'
  # @@protoc_insertion_point(class_scope:SavedSimulations.SimulationData)
  })
_sym_db.RegisterMessage(SimulationData)
_sym_db.RegisterMessage(SimulationData.ParameterFieldEntry)


# @@protoc_insertion_point(module_scope)
